import { Footer } from "@/components/layout/footer";
import { Navbar } from "@/components/layout/navbar";
import { getUserMe } from "@/features/auth/queries/get-user-me";
import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data: user } = await getUserMe();

  return (
    <html lang="en" className="italivo-legacy">
      <body className={`${playfair.variable} ${inter.variable} antialiased`}>
        <Navbar user={user ?? null} />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
